/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LCD.h"
#include "Teclado_MatrixKeyboard.h"
#include "Clock_1.h"
#include "ISR_Key.h"
#include "unlog_aliases.h"
#include "unlog.h"
#include "logoutisr.h"
#include "Contaor.h"
#include "Clock_2.h"
#include "UanMS.h"
#include "led_aliases.h"
#include "led.h"
#include "ADC.h"
#include "PWM.h"
#include "Clock_3.h"
#include "pwmpin_aliases.h"
#include "pwmpin.h"
#include "RTC.h"
#include "Seg_aliases.h"
#include "Com_aliases.h"
#include "LED_Driver_1.h"
#include "tempe_aliases.h"
#include "tempe.h"
#include "humed_aliases.h"
#include "humed.h"
#include "AMux_1.h"
#include "boton1_aliases.h"
#include "boton1.h"
#include "isr_b1.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "Teclado_Column_aliases.h"
#include "Teclado_Column.h"
#include "Teclado_Row_aliases.h"
#include "Teclado_Row.h"
#include "Teclado_Status_Reg.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "LED_Driver_1_ClkInternal.h"
#include "LED_Driver_1_Seg_Driver_L.h"
#include "LED_Driver_1_Com_Driver.h"
#include "LED_Driver_1_DMA_Com_dma.h"
#include "LED_Driver_1_DMA_Seg_dma.h"
#include "LED_Driver_1_DMA_BC_dma.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

